version: '3.8'
services:
  frontend:
    build: ./angularFront
    container_name: frontend
    restart: always

  backend:
    build: ./Spring-CrudApiRest/crudApiRest
    container_name: backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tu_basededatos
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=contraseña
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: tu_basededatos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data: